Lmod Warning: The system MODULEPATH has changed: please rebuild your saved
collection.



Traceback (most recent call last):
  File "/home/labs/mayalab/barc/MSc_studies/ML_Project/pyScripts/BarModels/RF_Main_Run_BestParams.py", line 304, in <module>
    main()
  File "/home/labs/mayalab/barc/MSc_studies/ML_Project/pyScripts/BarModels/RF_Main_Run_BestParams.py", line 296, in main
    generate_prediction_and_feature_tables(X_train, y_train, X_test, y_test, best_params, scores, scores_cm, scores_binary)
  File "/home/labs/mayalab/barc/MSc_studies/ML_Project/pyScripts/BarModels/RF_Main_Run_BestParams.py", line 247, in generate_prediction_and_feature_tables
    plt.savefig(os.path.join(here, 'results', 'feature_importance_plot.png'))
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1134, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 497, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 446, in _print_pil
    mpl.image.imsave(
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/matplotlib/image.py", line 1656, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/labs/mayalab/barc/.conda/envs/ml/lib/python3.9/site-packages/PIL/Image.py", line 2436, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'results/feature_importance.png'
